[Hodbptb]
;Driver=/usr/dlc113/odbc/lib/pgoe27.so
Driver = Progress113
DMEnvAttr = SQL_ATTR_UNIXODBC_ENVATTR={LD_LIBRARY_PATH=/usr/dlc113/odbc/lib:/usr/dlc113/lib}
DatabaseName = odbpta
PortNumber = 6008
HostName = 192.168.40.2
LogonID = admin
Password = admodbpta
DefaultIsolationLevel = REPEATABLE READ
StaticCursorLongColBuffLen = 4096
;ServerType=SQL
;[Hbmp]
;Driver=/usr/dlc113/odbc/lib/pgoe27.so
;Driver=Progress11.3
;DMEnvAttr = SQL_ATTR_UNIXODBC_ENVATTR={LD_LIBRARY_PATH=/usr/dlc113/odbc/lib:/usr/dlc113/lib}
;DatabaseName=bmp
;PortNumber=21211
;HostName=192.168.40.2
;LogonID=aistr
;Password=aispwd
;DefaultIsolationLevel=REPEATABLE READ
;StaticCursorLongColBuffLen = 4096
